export default {
  NOTE: "Note",
  USER: "User",
  LIST: "List",
  EMPLOYEE: "Employee",
  MANAGER: "Manager",
  ADMIN: "Admin",
  USER_REGEX: /^[A-z]{3,20}$/,
  PWD_REGEX: /^[A-z0-9!@#$%]{4,12}$/,
  EMAIL_REGEX: /^[A-z0-9._%+-]+@[A-z0-9.-]+\.[A-z]{2,4}$/,
  USER_URL: "/api/v1/users",
  NOTE_URL: "/api/v1/notes",
  HTTP_STATUS_OK: 200,
  SORT_EQUAL: 0,
  SORT_FIRST_BEFORE_SECOND: -1,
  SORT_FIRST_AFTER_SECOND: 1,
};
